---
  # - name: Decrypt AWS Credentials stored in Ansible Vault
  #   include_vars: vault.yml

  - name: Launch Simple CloudFormation
    cloudformation:
      stack_name: "ansible-cf-demo"
      state: "present"
      # aws_access_key: "{{ aws_access_key_id }}"
      # aws_secret_key: "{{ aws_secret_access_key }}"
      region: "{{ aws_region }}"
      disable_rollback: false
      template: "{{ role_path }}/files/cloudformation-simple.json"
      template_parameters:
        KeyName: "{{ aws_keyname }}"
        InstanceType: "{{ aws_instance_type }}"
        SubnetId: "{{ subnet_id }}"
        SecurityGroupId: "{{ security_group_id }}"
      tags:
        Stack: "ansible-cf-demo"
        Project: "Ansible CloudFormation Demo"
    register: stack

  - name: Show stack Outputs
    debug: msg="{{ stack.stack_outputs }}"

  - name: SSH Instructions
    debug: msg="Connect with ssh -i {{ aws_keyname }}.pem ec2-user@{{ stack.stack_outputs.PublicIP }}"
